### ISSUE TITLE
model config yaml files

### ISSUE THREAD

**Issue by mahaling** [alhojel/visual_task_vectors#3]
Just cloned the repo to try out the demo notebook. I am stuck with a "model.yaml" file not found error. 
I am missing running something before running the demo notebook?

Thanks

**Comment by alhojel** [comment]
Please follow the instructions to download the pre-trained models, checkpoint weights and .yaml at the bottom of the repo. Here is the link as well...

https://github.com/amirbar/visual_prompting

**Comment by mahaling** [comment]
thanks I was able to download the files.
